spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MCVV=TRUE
    username: sa
    passwowrd:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
 #       show_sql: true
        format_sql: true

l0gging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

